-- AlterTable
ALTER TABLE "schedules" ALTER COLUMN "accountId" DROP NOT NULL,
ALTER COLUMN "agentId" DROP NOT NULL,
ALTER COLUMN "startTime" DROP NOT NULL,
ALTER COLUMN "endTime" DROP NOT NULL;

-- AlterTable
ALTER TABLE "tasks" ALTER COLUMN "accountId" DROP NOT NULL,
ALTER COLUMN "startTime" DROP NOT NULL,
ALTER COLUMN "duration" DROP NOT NULL;
